# Site settings
title: Gimnasio Karate Kan
email: gimnasio@karatekan.es
description: > # this means to ignore newlines until "baseurl:"
  Tu gimnasio de artes marciales en Zaragoza. Pioneros en Karate Kyokushin.
  Ven a probar Boxeo, Judo, Aikido, Krav Maga, K-1, Total Entreno, Artes Marciales Mixtas (MMA), Jiu Jitsu Brasileño (BJJ) o Karate Infantil
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://karatekan.github.io" # the base hostname & protocol for your site
twitter_username: ClubKarateKan
facebook_username:  karate.kan

# Build settings
markdown: kramdown

paginate: 3
paginate_path: "blog/page:num"
sass:
  sass_dir: _sass
  style: compressed
