# Site settings
title: Gimnasio Karate Kan
email: gimnasio@karatekan.es
description: > # this means to ignore newlines until "baseurl:"
  Gimnasio de artes marciales en Zaragoza. Pioneros en Karate Kyokushin.
  Prueba Boxeo, Judo, Aikido, Krav Maga, K-1, MMA, BJJ o Karate Infantil
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.karatekan.es" # the base hostname & protocol for your site
twitter_username: ClubKarateKan
facebook_username:  karate.kan

# Build settings
markdown: kramdown

collections:
  activities:
    output: true
    permalink: /actividades/:path
  trainers:
    output: true
    permalink: /entrenadores/:path

defaults:
  -
    scope:
      path: ""
      type: activities
    values:
      layout: activity
  -
    scope:
      path: ""
      type: trainers
    values:
      layout: trainer

gems:
    - jekyll-paginate
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed

paginate: 12
paginate_path: "blog/page:num"
sass:
  sass_dir: _sass
  style: compressed
exclude: [vendor]
