- link: hector-lahoz
  name: Héctor Lahoz
  activity: Karate Kyokushin
  socials:
    - link: https://www.facebook.com/ector.troya
      icon: facebook

- link: javier-sanchez
  name: Javier Sánchez
  activity: Karate Kyokushin
  socials:
    - link: https://www.facebook.com/ShihanJavier
      icon: facebook

- link: yuro-pantiru
  name: Yuro Pantiru
  activity: Boxeo
  socials:
    - link: https://www.facebook.com/profile.php?id=100006402166586
      icon: facebook

- link: javier-izquierdo
  name: Javier Izquierdo
  activity: Judo
  socials:

- link: laurent-scotto
  name: Laurent Scotto
  activity: Krav Maga
  socials:
    - link: https://www.facebook.com/kravmagazaragoza.fekm.5
      icon: facebook

- link: wilson-ramos
  name: Wilson Ramos
  activity: Jiu Jitsu Brasileño (BJJ)
  socials:
    - link: https://www.facebook.com/wilson.ramos.71216
      icon: facebook

- link: alex-lutic
  name: Álex Lutic
  activity: K-1
  socials:
    - link: https://www.facebook.com/alexLutic1
      icon: facebook

- link: francisco-ferreira
  name: Francisco Ferreira
  activity: Artes Marciales Mixtas (MMA)
  socials:
    - link: https://www.facebook.com/francisco.ferreira.568
      icon: facebook

- link: marco-navarro
  name: Marco Navarro
  activity: Aikido
  socials:
    - link: https://www.facebook.com/marcoantonio.navarroramillete
      icon: facebook

- link: roberto-barra
  name: Roberto Barra
  activity: Aikido
  socials:
    - link: https://www.facebook.com/aikinomada.aikinomada
      icon: facebook

- link: antonio-pinero
  name: Antonio Piñero
  activity: Karate Kyokushin
  socials:

- link: jesus-baguena
  name: Jesús Baguena
  activity: Karate Kyokushin
  socials:
    - link: https://www.facebook.com/moterojesus
      icon: facebook
