- link: javier-izquierdo
  name: Javier Izquierdo
  activity: Judo
  socials:
    - link: http://facebook.com
      icon: facebook

- link: wilson-ramos
  name: Wilson Ramos
  activity: Jiu Jitsu Brasileño (BJJ)
  socials:
    - link: http://facebook.com
      icon: facebook

- link: alex-lutic
  name: Álex Lutic
  activity: K-1
  socials:
    - link: http://facebook.com
      icon: facebook

- link: laurent-scotto
  name: Laurent Scotto
  activity: Krav Maga
  socials:
    - link: http://facebook.com
      icon: facebook

- link: yuro-pantiru
  name: Yuro Pantiru
  activity: Boxeo
  socials:
    - link: http://facebook.com
      icon: facebook

- link: francisco-ferreira
  name: Francisco Ferreira
  activity: Artes Marciales Mixtas (MMA)
  socials:
    - link: http://facebook.com
      icon: facebook

- link: marco-navarro
  name: Marco Navarro
  activity: Aikido
  socials:
    - link: http://facebook.com
      icon: facebook

- link: roberto-barra
  name: Roberto Barra
  activity: Aikido
  socials:
    - link: http://facebook.com
      icon: facebook

- link: javier-sanchez
  name: Javier Sánchez
  activity: Karate Kyokushin
  socials:
    - link: http://facebook.com
      icon: facebook

- link: jesus-baguena
  name: Jesús Baguena
  activity: Karate Kyokushin
  socials:
    - link: http://facebook.com
      icon: facebook

- link: ivan-berned
  name: Iván Berned
  activity: Karate Kyokushin
  socials:
    - link: http://facebook.com
      icon: facebook

- link: antonio-pinero
  name: Antonio Piñero
  activity: Karate Kyokushin
  socials:
    - link: http://facebook.com
      icon: facebook

- link: hector-lahoz
  name: Héctor Lahoz
  activity: Karate Kyokushin
  socials:
    - link: http://facebook.com
      icon: facebook
