- link: javier_izquierdo
  name: Javier Izquierdo
  activity: Judo
  socials:
    - link: http://facebook.com
      icon: facebook

- link: wilson_ramos
  name: Wilson Ramos
  activity: Jiu Jitsu Brasileño (BJJ)
  socials:
    - link: http://facebook.com
      icon: facebook

- link: alex_lutic
  name: Alex Lutic
  activity: K-1
  socials:
    - link: http://facebook.com
      icon: facebook

- link: laurent_scotto
  name: Laurent Scotto
  activity: Krav Maga
  socials:
    - link: http://facebook.com
      icon: facebook

- link: yuro_pantiru
  name: Yuro Pantiru
  activity: Boxeo
  socials:
    - link: http://facebook.com
      icon: facebook

- link: francisco_ferreira
  name: Francisco Ferreira
  activity: Artes Marciales Mixtas (MMA)
  socials:
    - link: http://facebook.com
      icon: facebook

- link: marco_navarro
  name: Marco Navarro
  activity: Aikido
  socials:
    - link: http://facebook.com
      icon: facebook

- link: roberto_barra
  name: Roberto Barra
  activity: Aikido
  socials:
    - link: http://facebook.com
      icon: facebook

- link: javier_sanchez
  name: Javier Sánchez
  activity: Karate Kyokushin
  socials:
    - link: http://facebook.com
      icon: facebook

- link: jesus_baguena
  name: Jesús Baguena
  activity: Karate Kyokushin
  socials:
    - link: http://facebook.com
      icon: facebook

- link: ivan_berned
  name: Iván Berned
  activity: Karate Kyokushin
  socials:
    - link: http://facebook.com
      icon: facebook

- link: antonio_pinero
  name: Antonio Piñero
  activity: Karate Kyokushin
  socials:
    - link: http://facebook.com
      icon: facebook

- link: hector_lahoz
  name: Héctor Lahoz
  activity: Karate Kyokushin
  socials:
    - link: http://facebook.com
      icon: facebook
