- link: antonio-pinero
  name: Antonio Piñero
  activities:
    - Karate Kyokushin
  socials:

- link: javier-sanchez
  name: Javier Sánchez
  activities:
    - Karate Kyokushin
    - Gimnasia de Mantenimiento
  socials:
    - link: https://www.facebook.com/ShihanJavier
      icon: facebook

- link: hector-lahoz
  name: Héctor Lahoz
  activities:
    - Karate Kyokushin
    - Karate Infantil
    - Total Entreno
  socials:
    - link: https://www.facebook.com/ector.troya
      icon: facebook

- link: wilson-ramos
  name: Wilson Ramos
  activities:
    - Jiu Jitsu Brasileño (BJJ)
    - Artes Marciales Mixtas (MMA)
  socials:
    - link: https://www.facebook.com/wilson.ramos.71216
      icon: facebook

- link: javier-izquierdo
  name: Javier Izquierdo
  activities:
    - Judo
    - Aikido
  socials:

- link: jesus-baguena
  name: Jesús Baguena
  activities:
    - Karate Kyokushin
  socials:
    - link: https://www.facebook.com/moterojesus
      icon: facebook

- link: yuro-pantiru
  name: Yuro Pantiru
  activities:
    - Boxeo
    - Artes Marciales Mixtas (MMA)
  socials:
    - link: https://www.facebook.com/profile.php?id=100006402166586
      icon: facebook

- link: alex-lutic
  name: Álex Lutic
  activities:
    - K-1
    - Artes Marciales Mixtas (MMA)
  socials:
    - link: https://www.facebook.com/alexLutic1
      icon: facebook

- link: roberto-barra
  name: Roberto Barra
  activities:
    - Aikido
  socials:
    - link: https://www.facebook.com/aikinomada.aikinomada
      icon: facebook

- link: laurent-scotto
  name: Laurent Scotto
  activities:
    - Krav Maga
  socials:
    - link: http://kmzfekm.wix.com/kmzfekm
      icon: globe
    - link: https://www.facebook.com/kravmagazaragoza.fekm.5
      icon: facebook


- link: marco-navarro
  name: Marco Navarro
  activities:
  socials:
